ALTER TABLE normes
    ADD COLUMN IF NOT EXISTS pdf_path VARCHAR(500),
    ADD COLUMN IF NOT EXISTS pdf_original_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS pdf_content_type VARCHAR(120),
    ADD COLUMN IF NOT EXISTS pdf_size BIGINT;
